### ISSUE TITLE
.save errors out (canon 7d)

### ISSUE THREAD

**Issue by rubenbroman** [lonelyelk/gphoto4ruby#4]
I keep getting this error on the example.rb 

> gphototest.rb:30:in `save': LibGPhoto2 function returned: Unspecified error (GPhoto2::Exception)

Here's the full output. I've tried with both ruby 1.9.3 and 2.2.0.

1cameras connected
camera in port: usb:020,018
bulb value is: false
values available are: [true, false]
uilock value is: false
values available are: [true, false]
syncdatetime value is: false
values available are: [true, false]
autofocusdrive value is: false
values available are: [true, false]
manualfocusdrive value is: None
values available are: ["Near 1", "Near 2", "Near 3", "None", "Far 1", "Far 2", "Far 3"]
eoszoom value is: 0
values available are: []
eoszoomposition value is: 0,0
values available are: []
eosviewfinder value is: false
values available are: [true, false]
eosremoterelease value is: None
values available are: ["None", "Press Half", "Press Full", "Release Half", "Release Full", "Immediate", "Press 1", "Press 2", "Press 3", "Release 1", "Release 2", "Release 3"]
datetime value is: 2015-02-06 02:12:22 UTC
values available are: []
reviewtime value is: 2 seconds
values available are: ["None", "2 seconds", "4 seconds", "8 seconds", "Hold"]
output value is: Unknown value 0000
values available are: ["TFT", "PC", "Setting 4", "Unknown value 0000"]
movierecordtarget value is: None
values available are: ["Card", "None"]
evfmode value is: 1
values available are: ["0", "1"]
ownername value is: 
values available are: []
artist value is: 
values available are: []
copyright value is: 
values available are: []
customfuncex value is: 10,c189,d105,3,
values available are: []
autopoweroff value is: 900
values available are: []
capturetarget value is: Internal RAM
values available are: ["Internal RAM", "Memory card"]
capture value is: false
values available are: [true, false]
serialnumber value is: b3669130cddf4fd2a60d25e7b1a812e7
values available are: []
manufacturer value is: Canon Inc.
values available are: []
cameramodel value is: Canon EOS 7D
values available are: []
deviceversion value is: 3-1.0.8
values available are: []
vendorextension value is: None
values available are: []
model value is: 2147484240
values available are: []
ptpversion value is: 256
values available are: []
batterylevel value is: 100%
values available are: []
lensname value is: EF-S17-55mm f/2.8 IS USM
values available are: []
eosserialnumber value is: 230211240
values available are: []
shuttercounter value is: 16665
values available are: []
availableshots value is: 145633
values available are: []
imageformat value is: Small Fine JPEG
values available are: ["Large Fine JPEG", "Large Normal JPEG", "Medium Fine JPEG", "Medium Normal JPEG", "Small Fine JPEG", "Small Normal JPEG", "RAW + Large Fine JPEG", "RAW + Large Normal JPEG", "RAW + Medium Fine JPEG", "RAW + Medium Normal JPEG", "RAW + Small Fine JPEG", "RAW + Small Normal JPEG", "mRAW + Large Fine JPEG", "mRAW + Large Normal JPEG", "mRAW + Medium Fine JPEG", "mRAW + Medium Normal JPEG", "mRAW + Small Fine JPEG", "mRAW + Small Normal JPEG", "sRAW + Large Fine JPEG", "sRAW + Large Normal JPEG", "sRAW + Medium Fine JPEG", "sRAW + Medium Normal JPEG", "sRAW + Small Fine JPEG", "sRAW + Small Normal JPEG", "RAW", "mRAW", "sRAW"]
imageformatcf value is: Small Fine JPEG
values available are: ["Large Fine JPEG", "Large Normal JPEG", "Medium Fine JPEG", "Medium Normal JPEG", "Small Fine JPEG", "Small Normal JPEG", "RAW + Large Fine JPEG", "RAW + Large Normal JPEG", "RAW + Medium Fine JPEG", "RAW + Medium Normal JPEG", "RAW + Small Fine JPEG", "RAW + Small Normal JPEG", "mRAW + Large Fine JPEG", "mRAW + Large Normal JPEG", "mRAW + Medium Fine JPEG", "mRAW + Medium Normal JPEG", "mRAW + Small Fine JPEG", "mRAW + Small Normal JPEG", "sRAW + Large Fine JPEG", "sRAW + Large Normal JPEG", "sRAW + Medium Fine JPEG", "sRAW + Medium Normal JPEG", "sRAW + Small Fine JPEG", "sRAW + Small Normal JPEG", "RAW", "mRAW", "sRAW"]
imageformatexthd value is: Small Fine JPEG
values available are: ["Large Fine JPEG", "Large Normal JPEG", "Medium Fine JPEG", "Medium Normal JPEG", "Small Fine JPEG", "Small Normal JPEG", "RAW + Large Fine JPEG", "RAW + Large Normal JPEG", "RAW + Medium Fine JPEG", "RAW + Medium Normal JPEG", "RAW + Small Fine JPEG", "RAW + Small Normal JPEG", "mRAW + Large Fine JPEG", "mRAW + Large Normal JPEG", "mRAW + Medium Fine JPEG", "mRAW + Medium Normal JPEG", "mRAW + Small Fine JPEG", "mRAW + Small Normal JPEG", "sRAW + Large Fine JPEG", "sRAW + Large Normal JPEG", "sRAW + Medium Fine JPEG", "sRAW + Medium Normal JPEG", "sRAW + Small Fine JPEG", "sRAW + Small Normal JPEG", "RAW", "mRAW", "sRAW"]
iso value is: 100
values available are: ["Auto", "100", "125", "160", "200", "250", "320", "400", "500", "640", "800", "1000", "1250", "1600", "2000", "2500", "3200", "4000", "5000", "6400", "12800"]
whitebalance value is: Daylight
values available are: ["Auto", "Daylight", "Shadow", "Cloudy", "Tungsten", "Fluorescent", "Flash", "Manual", "Color Temperature"]
colortemperature value is: 5600
values available are: []
whitebalanceadjusta value is: 0
values available are: ["-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
whitebalanceadjustb value is: 0
values available are: ["-9", "-8", "-7", "-6", "-5", "-4", "-3", "-2", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
whitebalancexa value is: 0
values available are: []
whitebalancexb value is: 0
values available are: []
colorspace value is: sRGB
values available are: ["sRGB", "AdobeRGB"]
autoexposuremode value is: Manual
values available are: ["P", "TV", "AV", "Manual", "Bulb", "A_DEP", "DEP", "Custom", "Lock", "Green", "Night Portrait", "Sports", "Portrait", "Landscape", "Closeup", "Flash Off"]
drivemode value is: Continuous low speed
values available are: ["Single", "Continuous high speed", "Continuous low speed", "Timer 2 sec", "Timer 10 sec"]
picturestyle value is: User defined 3
values available are: ["Standard", "Portrait", "Landscape", "Neutral", "Faithful", "Monochrome", "User defined 1", "User defined 2", "User defined 3"]
aperture value is: 9
values available are: ["2.8", "3.2", "3.5", "4", "4.5", "5", "5.6", "6.3", "7.1", "8", "9", "10", "11", "13", "14", "16", "18", "20", "22"]
shutterspeed value is: 1/200
values available are: ["30", "25", "20", "15", "13", "10", "8", "6", "5", "4", "3.2", "2.5", "2", "1.6", "1.3", "1", "0.8", "0.6", "0.5", "0.4", "0.3", "1/4", "1/5", "1/6", "1/8", "1/10", "1/13", "1/15", "1/20", "1/25", "1/30", "1/40", "1/50", "1/60", "1/80", "1/100", "1/125", "1/160", "1/200", "1/250", "1/320", "1/400", "1/500", "1/640", "1/800", "1/1000", "1/1250", "1/1600", "1/2000", "1/2500", "1/3200", "1/4000", "1/5000", "1/6400", "1/8000"]
meteringmode value is: Center-weighted average
values available are: ["Evaluative", "Partial", "Spot", "Center-weighted average"]
bracketmode value is: 0
values available are: []
aeb value is: off
values available are: ["off", "+/- 1/3", "+/- 2/3", "+/- 1", "+/- 1 1/3", "+/- 1 2/3", "+/- 2", "+/- 2 1/3", "+/- 2 2/3", "+/- 3"]
d402 value is: Canon EOS 7D
values available are: []
d407 value is: 1
values available are: []
d406 value is: Windows/6.1.7601 MTPClassDriver/6.1.7600.16385
values available are: []
d303 value is: 1
values available are: []
files on camera: []
some folder stuff: ["store_00010001"]
gphototest.rb:30:in `save': LibGPhoto2 function returned: Unspecified error (GPhoto2::Exception)
    from gphototest.rb:30:in`<main>'

**Comment by rubenbroman** [comment]
After commenting out the preview capture in the example.rb everything is working great.

> cams.first.capture.save :type => :preview, :new_name => "PREVIEW.JPG"
